---
title: Isik 26 letter MEG dataset
toc: true
---

<p class="ethan_opening_paragraph" style="padding-bottom: 0% !important;">The Isik 26 letter MEG dataset was collected by <a href="https://cogsci.jhu.edu/directory/leyla-isik/">Leyla Isik</a> in Tommy Poggio’s lab and the MEG Lab at the McGovern Institute at MIT. The data was used in Figure 2b of the paper: <a href="https://journals.physiology.org/doi/full/10.1152/jn.00394.2013">The dynamics of invariant object recognition in the human visual system J. Neurophys 2014. </a>

The data consists of 306 channel (comprised of 102 magentometers, and 204 planar gradiometers) MEG recordings from an Elekta Neuromag Triux Scanner. One subject was shown 26 black, upper-case letters, on a white background, while their neural response was recorded in the MEG scanner. Each letter was presented approximately 50 times. The data is in raster-format, and each trial consists of 233 ms of baseline data where the subject viewed a fixation cross, followed by 50 ms of data when the subject viewed the image of one letter, and 417 ms of data when they again viewed a fixation cross.

The data is available in two formats - the raw MEG files output by the scanner (.fif format) and preprocessed data in <a href="http://www.readout.info/toolbox-design/data-formats/raster-format/">raster format.</a> The raw data download also includes a file with raster labels indicating which stimulus was shown in each trial.
<p style="padding-top: 2%; padding-bottom: 0%;"><a href="http://cbcl.mit.edu/people/emeyers/data/Isik_26_letter_MEG_raster_data.zip">Download the Isik 26 letter MEG dataset in raster format </a>   &emsp;    Note these datasets are large (2.5GB)</p>
<p style="padding-top: 1%; padding-bottom: 2%;"><a href="http://cbcl.mit.edu/people/emeyers/data/Isik_26letter_raw_data.zip">Download the Isik 26 letter MEG dataset in .fif format</a> </p>

